config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  get '/secret', to: 'pages#secret', as: 'secret'
  scope module: 'inputprocess' do
    # get '/brands', to: 'brands/index', as: 'brands'
    resources :sharelease
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inputprocess.rb
module Inputprocess
  def self.table_name_prefix
    'inputprocess_'
  end
end

app/models/inputprocess/brand.rb
class Inputprocess::Brand < ApplicationRecord
end

app/models/inputprocess/sharelease.rb
class Inputprocess::Sharelease < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :zxcvbnable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/inputprocess/brands_controller.rb
class Inputprocess::BrandsController < ApplicationController
  def index

  end
end

app/controllers/inputprocess/sharelease_controller.rb
class Inputprocess::ShareleaseController < ApplicationController
  def new
    # @sharelease = Inputprocess::ShareLease.new
  end
  def create
    render plain: Inputprocess::ShareLease.new.inspect
    # @sharelease = Inputprocess::ShareLease.new(sharelease_params)
    # if @sharelease.save
      # redirect_to @sharelease
    # else
    #   render 'new'
    # end
    # @sharelease.inspect
    # render plain: params[:sharelease].inspect
  end
  def edit
    @sharelease = Inputprocess::ShareLease.find(params[:id])
  end
  def update
    # @sharelease = Inputprocess::ShareLease.find(params[])
  end
  def delete
    @sharelease = Inputprocess::ShareLease.delete([params[:id]])
  end

  private
  def sharelease_params
    params.require(:sharelease).permit(:name, :model)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header(text)
    content_for(:header) { text.to_s }
  end
end

app/helpers/inputprocess/brands_helper.rb
module Inputprocess::BrandsHelper
end

app/helpers/inputprocess/sharelease_helper.rb
module Inputprocess::ShareleaseHelper
end

app/views/inputprocess/sharelease/new.html.erb
<h2><% header 'Share Your Lease' %></h2>
<%= form_for :sharelease, url: sharelease_index_path, method: :post do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :model %>
      <%= f.text_field :model, class: 'form-control' %>
    </div>

    <%= f.submit 'Share your Lease', class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarLease</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'Car Lease', root_path, class: 'navbar-brand' %>
        </div>
        <div id="navbar">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home', root_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to 'Secret', secret_path %></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav pull-right">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  <%= current_user.name %>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to 'Profile', edit_user_registration_path %></li>
                  <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to 'Sign In', new_user_session_path %></li>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
    </div>

    <%= yield :top_content %>

    <div class="container">
      <h1><%= yield :header %></h1>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<% content_for :top_content do %>
    <div class="jumbotron">
      <div class="container">
        <h1>Welcome!</h1>
        <p>Register to get started.</p>
        <p>
          <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
        </p>
      </div>
    </div>
<% end %>

app/views/pages/secret.html.erb
<% header 'Secret!' %>